export const createTextFormStructure = [
  {
    id: 1,
    placeholder: "Insert asset name",
    labelText: "Asset name",
    name: "name",
    inputMode: "default",
    type: "input",
    validators: {
      required: "This field is required",
    },
  },
  {
    id: 6,
    labelText: "Plan",
    type: "radio-button",
    name: "plan",
    defaultSelected: 'ownership',
    options: ["free", "ownership", "subscription"],
  },
  {
    id: 2,
    placeholder: "Insert asset price",
    labelText: "Asset price",
    name: "price",
    inputMode: "numeric",
    type: "input",
    validators: {
      required: "This field is required",
    },
  },
  {
    id: 7,
    placeholder: "Insert subscription period",
    labelText: "Subscription period",
    name: "subscription_period",
    inputMode: "numeric",
    type: "input",
    validators: {
      required: "This field is required",
    },
  },
  {
    id: 5,
    placeholder: "Insert asset description",
    labelText: "Asset description",
    name: "description",
    inputMode: "default",
    type: "input",
    validators: {
      required: "This field is required",
    },
  },
  // {
  //   id: 8,
  //   labelText: "Eligible for image extraction",
  //   name: 'eligible_for_image_extraction',
  //   type: "radio-button",
  //   defaultSelected: true,
  //   options: [true,false],
  // },
  // {
  //   id: 9,
  //   labelText: "Eligible for audio extraction",
  //   name: 'eligible_for_audio_extraction',
  //   type: "radio-button",
  //   defaultSelected: true,
  //   options: [true, false],
  // },
  // {
  //   id: 10,
  //   labelText: "Eligible for video extraction",
  //   name: 'eligible_for_video_extraction',
  //   type: "radio-button",
  //   defaultSelected: true,
  //   options: [true, false],
  // },
  {
    id: 10,
    labelText: "forkability status",
    name: 'forkability_status',
    type: "radio-button",
    defaultSelected: true,
    options: [true, false],
  },
  {
    id: 3,
    placeholder: "Insert asset content",
    labelText: "Asset content",
    name: "file",
    inputMode: "default",
    type: "textarea",
    validators: {
      required: "This field is required",
    },
  },
];
